import Head from 'next/head'
import Image from 'next/image'
import SearchBar from '../components/SearchBar'
import Coins from '../components/Coins'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <SearchBar type="text" placeholder="search"/>
        <Coins />
    </div>
  )
}
