import Head from "next/head";
import CoinsListContainer from "../components/Coins/CoinsListContainer";
import { useState } from "react";
import SearchBar from "../components/SearchBar/SearchBar";

export default function Home() {
  const [query, setQuery] = useState("");
  return (
    <div>
      <Head>
        <title>Crypto API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SearchBar type="text" placeholder="search" /> */}
      <SearchBar props={{ query, setQuery }} />
      <CoinsListContainer props={{ query }} />
    </div>
  );
}
