import Head from "next/head";
import CoinsListContainer from "../components/Coins/CoinsListContainer";
import { useState } from "react";
import SearchBar from "../components/SearchBar/SearchBar";
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import Dashboard from '../components/Dashboard/Dashboard';
import Preferences from '../components/Preferences/Preferences';
import App from "./App.js"

// This needs fixed here, I need to research which to use with next.js
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>, 
  document.getElementById('root')
);

export default function Home() {
  const [query, setQuery] = useState("");
  return (
    <div>
      <Head>
        <title>Crypto API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SearchBar type="text" placeholder="search" /> */}
      {/* <SearchBar props={{ query, setQuery }} />
      <CoinsListContainer props={{ query }} /> */}
      <App/>
    </div>
  );
}
